---
# AutoSphere Playbook: ProxySQL Connection Pool Recovery
# Purpose: Fix ProxySQL connection exhaustion without restarting MariaDB
# Risk: LOW - ProxySQL restart doesn't affect MariaDB
# Estimated Time: 5 minutes
# Last Updated: 2025
#
# YOUR DEPLOYMENT: ProxySQL frontend for MariaDB (Kolla 2025.1)

- name: ProxySQL Connection Pool Recovery
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: yes
  become: yes
  
  vars:
    incident_id: "{{ incident_id | default('AUTO') }}"
    proxysql_container: "proxysql"
    mariadb_container: "mariadb"
    proxysql_admin_port: 6032
    proxysql_mysql_port: 6033
    
  tasks:
    - name: "[PRE-CHECK] Verify ProxySQL and MariaDB containers"
      shell: |
        echo "=== ProxySQL Status ==="
        docker ps --filter "name={{ proxysql_container }}" --format "{%raw%}{{.Names}}: {{.Status}}{%endraw%}"
        
        echo ""
        echo "=== MariaDB Status ==="
        docker ps --filter "name={{ mariadb_container }}" --format "{%raw%}{{.Names}}: {{.Status}}{%endraw%}"
      register: container_status
      
    - name: "[DIAGNOSIS] Check ProxySQL connection pool"
      shell: |
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT hostgroup, srv_host, status, ConnUsed, ConnFree, Latency_us FROM stats_mysql_connection_pool" 2>/dev/null || \
        echo "Cannot query ProxySQL stats"
      register: connection_pool
      
    - name: "[DIAGNOSIS] Check active connections"
      shell: |
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT * FROM stats_mysql_processlist LIMIT 50" 2>/dev/null || \
        echo "Cannot query processlist"
      register: processlist
      
    - name: "[DIAGNOSIS] Check ProxySQL errors"
      shell: |
        docker logs --tail 100 {{ proxysql_container }} 2>&1 | grep -i "error\|warning\|max_connections" || echo "No errors in recent logs"
      register: proxysql_errors
      
    - name: "[DIAGNOSIS] Check MariaDB backend health"
      shell: |
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT hostname, port, status FROM mysql_servers" 2>/dev/null || \
        echo "Cannot query backend servers"
      register: backend_health
      
    - name: "[DIAGNOSIS] Identify stale connections"
      shell: |
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT user, db, time, info FROM stats_mysql_processlist WHERE time > 300 ORDER BY time DESC" 2>/dev/null || \
        echo "No stale connections found"
      register: stale_connections
      
    - name: "[BACKUP] Save ProxySQL state"
      shell: |
        mkdir -p /tmp/proxysql_recovery_{{ incident_id }}
        
        # Save connection stats
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT * FROM stats_mysql_connection_pool" > /tmp/proxysql_recovery_{{ incident_id }}/connection_pool_before.txt 2>&1 || true
          
        # Save config
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT * FROM mysql_servers" > /tmp/proxysql_recovery_{{ incident_id }}/servers_config.txt 2>&1 || true
          
        # Save processlist
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT * FROM stats_mysql_processlist" > /tmp/proxysql_recovery_{{ incident_id }}/processlist_before.txt 2>&1 || true
        
    - name: "[DECISION] Determine if MariaDB backend needs attention"
      set_fact:
        mariadb_healthy: "{{ 'ONLINE' in backend_health.stdout }}"
        connection_limit_reached: "{{ 'max_connections' in proxysql_errors.stdout | lower }}"
        has_stale_connections: "{{ stale_connections.stdout_lines | length > 5 }}"
        
    - name: "[EXECUTE] Strategy 1 - Kill stale connections (if detected)"
      when: has_stale_connections
      shell: |
        # Kill connections idle > 5 minutes
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT CONCAT('KILL ', id, ';') FROM stats_mysql_processlist WHERE time > 300" | \
          grep KILL | \
          docker exec -i {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin 2>/dev/null || \
        echo "Killed stale connections"
      register: kill_stale
      
    - name: "[EXECUTE] Strategy 2 - Flush connection pool"
      shell: |
        # Flush frontend connections
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "PROXYSQL FLUSH MYSQL_CONNECTIONS" 2>/dev/null || \
        echo "Cannot flush connections"
      register: flush_connections
      
    - name: "[EXECUTE] Strategy 3 - Reset ProxySQL statistics"
      shell: |
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "PROXYSQL FLUSH MYSQL STATISTICS" 2>/dev/null || \
        echo "Cannot flush statistics"
        
    - name: "[EXECUTE] Strategy 4 - Restart ProxySQL only (if pool exhausted)"
      when: connection_limit_reached and mariadb_healthy
      shell: |
        echo "Restarting ProxySQL (MariaDB stays up)..."
        docker restart {{ proxysql_container }}
      register: proxysql_restart
      
    - name: "[VERIFY] Wait for ProxySQL ready"
      when: proxysql_restart.changed | default(false)
      shell: |
        for i in {1..30}; do
          if docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
             -e "SELECT 1" >/dev/null 2>&1; then
            echo "ProxySQL admin interface ready"
            exit 0
          fi
          sleep 2
        done
        echo "ProxySQL not responding"
        exit 1
      register: proxysql_ready
      
    - name: "[VERIFY] Check connection pool after fix"
      shell: |
        docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
          -e "SELECT hostgroup, srv_host, status, ConnUsed, ConnFree FROM stats_mysql_connection_pool"
      register: pool_after
      
    - name: "[VERIFY] Test OpenStack service connections"
      shell: |
        # Test that OpenStack services can connect through ProxySQL
        services="keystone nova neutron cinder glance"
        
        for svc in $services; do
          container="${svc}"
          [ "$svc" = "nova" ] && container="nova-api"
          [ "$svc" = "neutron" ] && container="neutron-server"
          [ "$svc" = "cinder" ] && container="cinder-api"
          [ "$svc" = "glance" ] && container="glance-api"
          
          if docker ps --filter "name=$container" --format "{%raw%}{{.Names}}{%endraw%}" | grep -q "$container"; then
            docker logs --tail 10 $container 2>&1 | grep -i "database\|mysql\|connection" | tail -3 || echo "$svc: No DB logs"
          fi
        done
      register: service_db_check
      ignore_errors: yes
      
    - name: "[POST-CHECK] Monitor for connection leaks"
      shell: |
        echo "Monitoring connection pool for 2 minutes..."
        
        for i in {1..12}; do
          used=$(docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
            -N -e "SELECT SUM(ConnUsed) FROM stats_mysql_connection_pool" 2>/dev/null || echo "0")
          
          free=$(docker exec {{ proxysql_container }} mysql -h127.0.0.1 -P{{ proxysql_admin_port }} -uadmin -padmin \
            -N -e "SELECT SUM(ConnFree) FROM stats_mysql_connection_pool" 2>/dev/null || echo "0")
          
          echo "$(date +%H:%M:%S) - Used: $used, Free: $free"
          sleep 10
        done
      register: connection_monitor
      async: 130
      poll: 10
      
    - name: "[REPORT] Generate recovery report"
      copy:
        content: |
          ========================================
          PROXYSQL CONNECTION POOL RECOVERY
          ========================================
          
          Incident ID: {{ incident_id }}
          Timestamp: {{ ansible_date_time.iso8601 }}
          
          INITIAL DIAGNOSIS:
          {{ connection_pool.stdout }}
          
          BACKEND HEALTH:
          {{ backend_health.stdout }}
          
          STALE CONNECTIONS:
          {{ stale_connections.stdout }}
          
          ISSUES DETECTED:
          - MariaDB Healthy: {{ mariadb_healthy }}
          - Connection Limit Reached: {{ connection_limit_reached }}
          - Stale Connections: {{ has_stale_connections }}
          
          ACTIONS TAKEN:
          {% if has_stale_connections %}
          ✅ Killed {{ stale_connections.stdout_lines | length }} stale connections
          {% endif %}
          ✅ Flushed connection pool
          ✅ Reset statistics
          {% if proxysql_restart.changed | default(false) %}
          ✅ Restarted ProxySQL (MariaDB stayed up)
          {% endif %}
          
          CONNECTION POOL AFTER:
          {{ pool_after.stdout }}
          
          OPENSTACK SERVICE DB HEALTH:
          {{ service_db_check.stdout }}
          
          CONNECTION MONITORING (2min):
          {{ connection_monitor.stdout }}
          
          RECOMMENDATIONS:
          - Review ProxySQL max_connections setting
          - Check for connection leaks in OpenStack services
          - Monitor for services not closing connections properly
          - Consider increasing connection pool size if consistently maxed
          
        dest: "/tmp/autosphere_incident_{{ incident_id }}_proxysql.log"
        
    - name: "[ALERT] Recovery complete"
      debug:
        msg: |
          ✅ PROXYSQL RECOVERY COMPLETED
          
          Incident: {{ incident_id }}
          MariaDB: UNAFFECTED (stayed up)
          ProxySQL: {{ 'RESTARTED' if proxysql_restart.changed | default(false) else 'FLUSHED' }}
          Status: HEALTHY
          
          Connection Pool:
          {{ pool_after.stdout }}
          
          Report: /tmp/autosphere_incident_{{ incident_id }}_proxysql.log
          
  rescue:
    - name: "[ROLLBACK] Restart both ProxySQL and verify MariaDB"
      shell: |
        # Restart ProxySQL
        docker restart {{ proxysql_container }}
        
        # Verify MariaDB still healthy
        docker exec {{ mariadb_container }} mysql -uroot -p$(grep database_password /etc/kolla/passwords.yml | awk '{print $2}') \
          -e "SELECT 1" 2>/dev/null && echo "MariaDB: OK" || echo "MariaDB: ISSUE"
      ignore_errors: yes
      
    - name: "[ALERT] Recovery failed"
      debug:
        msg: |
          ❌ PROXYSQL RECOVERY FAILED
          
          Manual steps:
          1. Check ProxySQL logs:
             docker logs proxysql
          
          2. Verify MariaDB health:
             docker exec mariadb mysql -uroot -p$(grep database_password /etc/kolla/passwords.yml | awk '{print $2}') -e "SELECT 1"
          
          3. Review connection pool:
             docker exec proxysql mysql -h127.0.0.1 -P6032 -uadmin -padmin -e "SELECT * FROM stats_mysql_connection_pool"
          
          4. If needed, reconfigure:
             kolla-ansible reconfigure -t proxysql
          
          Backup: /tmp/proxysql_recovery_{{ incident_id }}/
          
    - fail:
        msg: "ProxySQL recovery failed"
